// serve/src/www/react-app/src/App.js
import React, { useState } from "react";
import GridComponent from "./GridComponent.js";
import "./App.css";

const MIN_STRETCH = 0.0;
const MAX_STRETCH = 1.0;
const STRETCH_STEP = 0.01;

function StretchComponent({ stretch, setStretch, setMaximumStretch }) {
  return (
    <div className="StretchComponent">
      <input
        type="range"
        value={stretch}
        min={MIN_STRETCH}
        max={MAX_STRETCH}
        step={STRETCH_STEP}
        onChange={event => setStretch(event.target.value)}
      />
      <div>{stretch}</div>
      <button onClick={setMaximumStretch}>Stretch to Grid</button>
    </div>
  );
}

function App() {
  const [stretch, setStretch] = useState(0.0);

  function setMaximumStretch() {
    setStretch(MAX_STRETCH);
  }

  return (
    <div className="App">
      <StretchComponent
        stretch={stretch}
        setStretch={setStretch}
        setMaximumStretch={setMaximumStretch}
      />
      <GridComponent
        layoutName="layout"
        setMaximumStretch={setMaximumStretch}
      />
    </div>
  );
}

export default App;

// serve/src/www/svelte/src/App.svelte
<script>
  export let strength;

  $: console.log("strength", strength);

  function stretchToGrid() {
    strength = 1.0;
  }
</script>

<style>

</style>

<input
  id="strength"
  type="range"
  min="0.0"
  max="1.0"
  step="0.01"
  bind:value={strength}
  style="width: 50%" />
<label for="strength">{strength}</label>

<button on:click={stretchToGrid}>Stretch to real grid</button>
